def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]

pipeline {
    
	agent any

    tools {
        maven "Maven3"
        jdk "OracleJDK8"
    }
/*	
	tools {
        maven "maven3"
    }
*/	
    environment {
        JAVA_HOME = '/usr/lib/jvm/java-1.8.0-openjdk-amd64'
 
        cluster = 'vprofileprod'
        service = 'vproappprodsvc'
    }
	
    stages{
        
       
        stage('Deploy to ECS prod'){
            steps{
                withAWS(credentials: 'awscreds', region : 'us-east-1'){
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }

	


    }
    
    post {
        always {
            echo 'Slack Notifications.'
            slackSend channel: '#devops-project',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }


}
